### PR TITLE
Navigation back event fixes for landscape orientation

### LINKED ISSUE #393: App keeps switching my tablet to Portrait mode
**Describe the bug**
Whenever I press the back button on my tablet while watching a stream, the app will automatically switch my tablet to Portrait mode despite orientation being locked to Landscape. The tablet stays in Portrait mode even after exiting the app and I need to unlock, rotate the screen and re-lock it. 

**To Reproduce**
Start a stream in Fullscreen landscape mode. 
Press the back button on the tablet
Notice the whole tablet switching to Portrait mode

**Expected behavior**
App should respect the current orientation set at the OS level and not change it. 

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6]: Fire HD 10 (11th Gen)
 - Android Version: [e.g. Android 12]: I can't seem to find the OS version anywhere in FireOS? Closest I have is a "Build Number: 0021274105476"
 - Twire Version: [e.g. 2.10.3]: Twire version 2.10.4

### PR DESCRIPTION
**Pull request by tim-crisp**
Closes #393.

When a live stream activity is created in landscape mode, I would expect that a back navigation would cause the live stream itself to be closed and not to be put in portrait mode (as it did in v2.10.3). In v2.10.4 as part of the [StreamFragment refactor](https://github.com/twireapp/Twire/compare/v2.10.3...twireapp:Twire:v2.10.4#diff-9b21c9fa2fb704b8990760ed90c86e1d868bb74e250e012dbff58858aa1204ee), the [isFullscreen](https://github.com/twireapp/Twire/compare/v2.10.3...twireapp:Twire:v2.10.4#diff-9b21c9fa2fb704b8990760ed90c86e1d868bb74e250e012dbff58858aa1204eeL131) boolean was previously used to determine whether to toggle fullscreen or not [when a back navigation event occurred](https://github.com/twireapp/Twire/compare/v2.10.3...twireapp:Twire:v2.10.4#diff-628667984cd6400d805a39adbb5f74c067f1670a02949148d6ad1dcb59a8af01L118). In version v2.10.3 the isFullscreen flag would only ever change if the user was to manually switch to fullscreen. As part of the v2.10.4 refactor, this now relies on [dynamically evaluating the current orientation](https://github.com/twireapp/Twire/compare/v2.10.3...twireapp:Twire:v2.10.4#diff-628667984cd6400d805a39adbb5f74c067f1670a02949148d6ad1dcb59a8af01R118) without considering the users initial orientation. I've introduced [StreamFragment#getInitialOrientation](https://github.com/twireapp/Twire/compare/master...tim-crisp:Twire:tablet-fixes?expand=1#diff-9b21c9fa2fb704b8990760ed90c86e1d868bb74e250e012dbff58858aa1204eeR1147-R1149) which exposes the initial orientation at the point of which a [StreamFragment was created](https://github.com/twireapp/Twire/compare/master...tim-crisp:Twire:tablet-fixes?expand=1#diff-9b21c9fa2fb704b8990760ed90c86e1d868bb74e250e012dbff58858aa1204eeR266). This is then used in [StreamActivity#onBackPressed](https://github.com/twireapp/Twire/compare/master...tim-crisp:Twire:tablet-fixes?expand=1#diff-628667984cd6400d805a39adbb5f74c067f1670a02949148d6ad1dcb59a8af01R118-R120) to determine whether we should be toggling full screen or not given the current orientation is landscape.
**Visual Representation:**
image

I've also [reduced the minimum chat size threshold](https://github.com/twireapp/Twire/compare/master...tim-crisp:Twire:tablet-fixes?expand=1#diff-4f5537c9e98b5b681f06e1940056acc6623f85adbadfa3bb17bd5e554647bd0bR166) to better cater for larger tablets.

FYI: I don't often write OOP and have only ever worked on personal android apps.

### CODE REVIEW

File: app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java [hunk 1]
```diff
@@ -262,6 +263,8 @@ public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
         final View mRootView = inflater.inflate(R.layout.fragment_stream, container, false);
         mRootView.requestLayout();
 
+        initialOrientation = getResources().getConfiguration().orientation;
```
Comment (samfundev) [inline app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java:266]: Could this be moved to the StreamActivity? Since the StreamFragment doesn't use this information.

**Review by samfundev — CHANGES_REQUESTED** [review]
